# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kontext < Formula
  desc "A CLI tool for managing Kubernetes contexts"
  homepage "https://github.com/user-cube/kontext"
  version "1.4.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/user-cube/kontext/releases/download/v1.4.0/kontext_1.4.0_darwin_amd64.tar.gz"
      sha256 "33a0cf6e5fd293da26420df6e2c58fe4688b3e412292275d32689b6964291c27"

      define_method(:install) do
        bin.install "kontext"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/user-cube/kontext/releases/download/v1.4.0/kontext_1.4.0_darwin_arm64.tar.gz"
      sha256 "03ddc1dd95caaad47e387cd1cac86674f4925f403e2ba5aebdb2fdb0ced4f39a"

      define_method(:install) do
        bin.install "kontext"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/user-cube/kontext/releases/download/v1.4.0/kontext_1.4.0_linux_amd64.tar.gz"
      sha256 "0ad6f96129201df4e7a4225b5e7083915a85fdf71fff383d1ef452f6225fe689"
      define_method(:install) do
        bin.install "kontext"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/user-cube/kontext/releases/download/v1.4.0/kontext_1.4.0_linux_arm64.tar.gz"
      sha256 "f85fbcb0b071e510ea8ef4d90928f672ea355810ee81c7e290956d3c10410642"
      define_method(:install) do
        bin.install "kontext"
      end
    end
  end

  test do
    system "#{bin}/kontext", "version"
  end
end
