# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsCliManager < Formula
  desc "CLI tool for managing AWS CLI"
  homepage "https://github.com/user-cube/aws-cli-manager"
  version "2.3.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/user-cube/aws-cli-manager/releases/download/v2.3.3/aws-cli-manager_2.3.3_darwin_amd64.tar.gz"
      sha256 "3c87db1e2f6b34cd5961ed6a8131d9d57943d639c91a4754859526cd76a34039"

      define_method(:install) do
        bin.install "aws-cli-manager"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/user-cube/aws-cli-manager/releases/download/v2.3.3/aws-cli-manager_2.3.3_darwin_arm64.tar.gz"
      sha256 "e1f1506f2f11bffebc4d3b90077df35b049251d1e97f5c736164e9c987da32ea"

      define_method(:install) do
        bin.install "aws-cli-manager"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/user-cube/aws-cli-manager/releases/download/v2.3.3/aws-cli-manager_2.3.3_linux_amd64.tar.gz"
      sha256 "e70b46eefec6f2491c83d4349247dc936a24aa1a23ef021bcb72534efe828c84"
      define_method(:install) do
        bin.install "aws-cli-manager"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/user-cube/aws-cli-manager/releases/download/v2.3.3/aws-cli-manager_2.3.3_linux_arm64.tar.gz"
      sha256 "03a386025eeadae2ae03199dd7fd86d95e740883149191056dfe8fc7c194433b"
      define_method(:install) do
        bin.install "aws-cli-manager"
      end
    end
  end

  test do
    system "#{bin}/aws-cli-manager", "version"
  end
end
