# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsCliManager < Formula
  desc "CLI tool for managing AWS CLI"
  homepage "https://github.com/user-cube/aws-cli-manager"
  version "2.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/user-cube/aws-cli-manager/releases/download/v2.3.0/aws-cli-manager_2.3.0_darwin_amd64.tar.gz"
      sha256 "d5b4e4ae2f97bae63800be76cb746fe244df8c09056cd573ea5b65d45402f6aa"

      define_method(:install) do
        bin.install "aws-cli-manager"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/user-cube/aws-cli-manager/releases/download/v2.3.0/aws-cli-manager_2.3.0_darwin_arm64.tar.gz"
      sha256 "6fae20c3d11865f9f3050be854bc84f7242f84044523c7a6ff81785f6a52a24f"

      define_method(:install) do
        bin.install "aws-cli-manager"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/user-cube/aws-cli-manager/releases/download/v2.3.0/aws-cli-manager_2.3.0_linux_amd64.tar.gz"
      sha256 "9d1aa5224fa05815b11001feee49e33d0a788859cd335058c5d141ad1dfe0874"
      define_method(:install) do
        bin.install "aws-cli-manager"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/user-cube/aws-cli-manager/releases/download/v2.3.0/aws-cli-manager_2.3.0_linux_arm64.tar.gz"
      sha256 "6e06983ba37cea6d8d6c25270d9a27951c91ec583d99711ccc48d18c4259cba8"
      define_method(:install) do
        bin.install "aws-cli-manager"
      end
    end
  end

  test do
    system "#{bin}/aws-cli-manager", "version"
  end
end
