# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClusterBootstrapCli < Formula
  desc "CLI tool to bootstrap Kubernetes clusters"
  homepage "https://github.com/user-cube/cluster-bootstrap"
  version "1.7.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/user-cube/cluster-bootstrap/releases/download/v1.7.2/cluster-bootstrap-cli-darwin-amd64.tar.gz"
      sha256 "4dfa4cf3fcd889352775fdf7f1dece2711d29acf69501938522ee7429526a0cc"

      define_method(:install) do
        bin.install "cluster-bootstrap-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/user-cube/cluster-bootstrap/releases/download/v1.7.2/cluster-bootstrap-cli-darwin-arm64.tar.gz"
      sha256 "4c368228276e876acbef5a780a0cef385ca55b52ae70c5e301fffe32c8ae708f"

      define_method(:install) do
        bin.install "cluster-bootstrap-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/user-cube/cluster-bootstrap/releases/download/v1.7.2/cluster-bootstrap-cli-linux-amd64.tar.gz"
      sha256 "cd5d785217041e415fcfd06783cc33699c842a6fb8a95ff18199c30e0d0a87ae"
      define_method(:install) do
        bin.install "cluster-bootstrap-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/user-cube/cluster-bootstrap/releases/download/v1.7.2/cluster-bootstrap-cli-linux-arm64.tar.gz"
      sha256 "f12ad28cbdf465e19865951e2dd436854314694b6418b5d4086e1c3733e80d87"
      define_method(:install) do
        bin.install "cluster-bootstrap-cli"
      end
    end
  end

  test do
    system "#{bin}/cluster-bootstrap-cli", "version"
  end
end
