# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kontext < Formula
  desc "CLI tool for managing Kubernetes contexts"
  homepage "https://github.com/user-cube/kontext"
  version "1.3.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/user-cube/kontext/releases/download/v1.3.2/kontext_1.3.2_darwin_amd64.tar.gz"
      sha256 "5173d6def98df88513e238379bb1fcf4c08a34fa40bc24326099ca96f2dfbf9c"

      define_method(:install) do
        bin.install "kontext"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/user-cube/kontext/releases/download/v1.3.2/kontext_1.3.2_darwin_arm64.tar.gz"
      sha256 "de6de2f5ceced10b80629000fcd0a0dc7ebd8db2da10dbe72c1dbb462b446390"

      define_method(:install) do
        bin.install "kontext"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/user-cube/kontext/releases/download/v1.3.2/kontext_1.3.2_linux_amd64.tar.gz"
      sha256 "def98b8ecb8cce8013236ffe5394db1c2b4736f7199602bcbdbfc4250507df42"
      define_method(:install) do
        bin.install "kontext"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/user-cube/kontext/releases/download/v1.3.2/kontext_1.3.2_linux_arm64.tar.gz"
      sha256 "4e386c88b95bfe4eee32ad13a45965275cd896286b7fffde8f65c68b1f908b45"
      define_method(:install) do
        bin.install "kontext"
      end
    end
  end

  test do
    system "#{bin}/kontext", "version"
  end
end
