# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kontext < Formula
  desc "CLI tool for managing Kubernetes contexts"
  homepage "https://github.com/user-cube/kontext"
  version "1.3.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/user-cube/kontext/releases/download/v1.3.1/kontext_1.3.1_darwin_amd64.tar.gz"
      sha256 "2e9505578e3b61e1c1895739c56332bb285616c66c024d6b37df855cef3f24d3"

      define_method(:install) do
        bin.install "kontext"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/user-cube/kontext/releases/download/v1.3.1/kontext_1.3.1_darwin_arm64.tar.gz"
      sha256 "e76ba61cf9ba14713a475e455cbdc1153dbc5d571d041c40e92443d2238c1afb"

      define_method(:install) do
        bin.install "kontext"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/user-cube/kontext/releases/download/v1.3.1/kontext_1.3.1_linux_amd64.tar.gz"
      sha256 "e99974703ebdd3d93977a2b6f9c0c9b7e576e609d8eb491e8efb373d67bc162f"
      define_method(:install) do
        bin.install "kontext"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/user-cube/kontext/releases/download/v1.3.1/kontext_1.3.1_linux_arm64.tar.gz"
      sha256 "08dad567e2686a4af9df8a1d71b57bdb5fa2d581143add4a6605ad954b216cca"
      define_method(:install) do
        bin.install "kontext"
      end
    end
  end

  test do
    system "#{bin}/kontext", "version"
  end
end
